### ISSUE TITLE
there is a bug?

### ISSUE THREAD

**Issue by sannyii** [astwyg/mask_watcher#1]
D:\mask_watcher>python watcher.py
Traceback (most recent call last):
  File "watcher.py", line 3, in <module>
    from log.logger import logger as log
  File "D:\mask_watcher\log\logger.py", line 8, in <module>
    file_handler = logging.FileHandler(os.path.join(os.path.abspath(os.path.dirname(__file__)), "logs", "log_{}.txt".format(time.strftime("%d_%m_%Y"))))
  File "C:\Users\erxia\AppData\Local\Programs\Python\Python37-32\lib\logging\__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\erxia\AppData\Local\Programs\Python\Python37-32\lib\logging\__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\mask_watcher\\log\\logs\\log_01_02_2020.txt'

**Comment by ohMyJason** [comment]
我也是

**Comment by ming076** [comment]
这个是需要自己在log目录下创建logs子目录，以及新建今天的日志文件，按照提示的创建就Ok了。
'D:\mask_watcher\log\logs\log_01_02_2020.txt'

**Comment by astwyg** [comment]
需要在项目目录下新建`log\logs`
