### ISSUE TITLE
Mac下的版本？

### ISSUE THREAD

**Issue by Megappp** [astwyg/mask_watcher#4]
Traceback (most recent call last):
  File "/Users/wenzhao/Downloads/mask_watcher-master/src/watcher.py", line 44, in <module>
    browser = webdriver.Chrome(os.path.join(os.path.dirname(__file__), "chromedriver.exe"))
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

看起来是因为无法调用Chrome？

**Comment by Megappp** [comment]
琢磨了一下。
Mac下自行下载chromedriver 拖到bin目录
然后   browser = webdriver.Chrome()
即可 
完美使用中 感谢老板

**Comment by astwyg** [comment]
你是对的, 需要根据OS下载对应的chrome driver
